# Generated by Django 3.1 on 2020-09-01 21:29

import uuid

import django.core.validators
from django.db import migrations, models

import pycpfcnpj.cpfcnpj


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "cnpj",
                    models.CharField(
                        max_length=18,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(18),
                            pycpfcnpj.cpfcnpj.validate,
                        ],
                    ),
                ),
                ("owner", models.CharField(max_length=40)),
                (
                    "ddd",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.MaxLengthValidator(2),
                        ]
                    ),
                ),
                (
                    "phone",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinLengthValidator(9),
                            django.core.validators.MaxLengthValidator(9),
                        ]
                    ),
                ),
            ],
        ),
    ]
