# Generated by Django 3.1 on 2020-09-05 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="ddd",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(2),
                    django.core.validators.MinValueValidator(11),
                    django.core.validators.MaxValueValidator(99),
                ]
            ),
        ),
    ]
