name: payments
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    name: Testing flow
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: shipay
          POSTGRES_PASSWORD: shipay
          POSTGRES_DB: shipay
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Set environment variables
        uses: allenevans/set-env@v1.0.0
        with:
          DB_NAME: shipay
          DB_USER: shipay
          DB_PASSWORD: shipay
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Perform linting tests
        run: |
          pre-commit run -a
      - name: Run unit tests
        run: |
          python manage.py test -v 2
